Records
rftafas/hdltools pull request #6
Opened 2020-12-20 20:12 UTC by tpcorrea

This branch substitute the input and output ports by only one input and one output using self-generated records. The script takes care of the connections between ports and internal registers, independent of the register type (ReadOnly, Write2Clear, Write2Pulse, etc). The generated vhdl file has no compile errors (tested with GHDL), but I didn't checked that is functionally correct.

2020-12-21 01:57 UTC, tpcorrea commented
Now with the option to use either options (with or without records)

2020-12-21 12:09 UTC, rftafas commented
There is a rebase missing first, as several changes and naming conventions were updated. Please, do this first.

Second, one important thing: I like the idea to pack stuff in records, but maybe we would get the best of 2 worlds by allowing several different records while also adding lone ports.

2020-12-21 12:22 UTC, tpcorrea commented
Are you sure? In my forked repo I could merge it with the master branch without any conflicts (also github tells it). 

About the "best of 2 worlds", I agree, but I see it is an evolution with lower priority when compared to adding a test bench (my next contribution), a header and a doc generator.

2020-12-21 19:44 UTC, rftafas requested changes
libPkg instead of package, seems to me we would not fall into confusion. these packages are part of the dictionary element that contains it. It would take some effort to mix them up. I don't think that necessary.
package class will be in the "front line" with its own methods.
---
For the record: I got the idea, this PR has a lot of improvements I'd like to get. I suggest to separate it into 3, one for the changes before libpkg and records (to be accepted ASAP) and 1 for libpkg and other for records. I may want to add effort to record improvement to make it more flexible and "per element".

2020-12-21 20:18 UTC, tpcorrea commented
Tafas, let me just understand how can I help here. Your suggestion is to keep the member as package and not libPkg, right? I could change it back and make a new commit with this change.

Can you merge a previous commit inside my branch, or may be cherry pick the changes? Please advise.

2020-12-22 12:54 UTC, rftafas commented
> Tafas, let me just understand how can I help here. Your suggestion is to keep the member as package and not libPkg, right? I could change it back and make a new commit with this change.
> 
> Can you merge a previous commit inside my branch, or may be cherry pick the changes? Please advise.

1. yes. This is one thing. I advise to revert, as we have the packageBody and packageDeclaration taht together with the libraryObj create package files.
2. For the several coding styles, new structures and reorganization related but independent to record in/output itself should be a different PR. They are ok, I'd like them on master branch.
3. I agree that we have more to focus than the record (simulation, for example). I'm still thinking on a more generic way to do the records so for a while, I'll create a record branch and you can push to this branch instead of master. Those willing to use it as it is will be able to do so and I'll rebase it until a more definite solution is set.
4. Finally, the records. I added the "pkgVHDL" class, it should be used by the regbank to create the pkg containing the records.

2020-12-22 19:13 UTC, tpcorrea commented
I did an independent PR, as you requested in (2). We can drop this one till we get a more mature implementation.

2020-12-22 19:13 UTC, closed without merging